"""empty message

Revision ID: c9537db78e3f
Revises:
Create Date: 2024-07-08 00:29:54.946592+00:00

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c9537db78e3f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'industrial_structure_edges',
        sa.Column('previous_item_id', sa.Integer(), nullable=False),
        sa.Column('next_item_id', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint(
            'previous_item_id',
            'next_item_id',
            name=op.f('pk_industrial_structure_edges')
        )
    )
    op.create_table(
        'industrial_structure_items',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False, comment='Наименование'),
        sa.PrimaryKeyConstraint(
            'id', name=op.f('pk_industrial_structure_items')
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('industrial_structure_items')
    op.drop_table('industrial_structure_edges')
    # ### end Alembic commands ###
